name: Java Selenium Automation

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 13 * * *' # Setiap hari jam 20:00 WIB (13:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Chrome untuk Selenium
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 4. Compile Java files
      - name: Compile Java files
        run: |
          mkdir -p bin
          javac -cp "lib/*" -d bin src/*.java

      # 5. Jalankan automation test
      - name: Run Automation Test
        run: java -cp "lib/*:bin" App