name: Java Selenium Automation

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 13 * * *'  # Setiap hari jam 20:00 WIB (13:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Compile Java files
        run: |
          mkdir -p bin
          javac -cp "lib/*" -d bin src/*.java

      - name: Run Automation Test
        run: java -cp "lib/*:bin" App